version: '3.6'

services:
  api_web:
    build:
      context: .

    ports:
    - "8000:8000"
    volumes:
    - /nfs:/nfs:shared
    container_name: api_web
    network_mode: "default"
    restart: 'always'
